- name: Deploy bloomcatcher server
  hosts: homelab
  tasks:
    - name: Ensure "nodejs" package is installed
      become: yes
      ansible.builtin.apt:
        name: nodejs

    - name: Ensure repos directory exists
      ansible.builtin.file:
        path: /home/dan/Documents/repos
        state: directory

    - name: checkout bloomcatcher repo
      ansible.builtin.git:
        repo: git@github.com:dandelany/bloomcatcher.git
        dest: "/home/dan/Documents/repos/bloomcatcher"
        version: master
        accept_hostkey: true

    - name: restart pm2 service
      ansible.builtin.command: pm2 startOrRestart ecosystem.config.js
      args:
        chdir: /home/dan/Documents/repos/bloomcatcher/server
    # rebuild client

    # TODO: npm install

#    - name: Install "pm2" node.js package globally.
#      community.general.npm:
#        name: pm2
#        global: true

