all:
  # hosts:
    # claude:
    #   # ansible_host: 192.168.1.153
    #   ansible_host: claude.local
    #   ansible_user: pi
    # georgia:
    #   ansible_host: georgia.local
    #   ansible_user: pi
    # vincent:
    #   ansible_host: vincent.local
    #   ansible_user: pi
  children:
#    lab_cameras:
#      hosts:
#        georgia:
#          ansible_host: georgia.local
#          ansible_user: pi
    setup_cameras:
      hosts:
        vincent:
          ansible_host: vincent.local
          ansible_user: pi

    field_cameras:
      hosts:
        claude:
          # ansible_host: 192.168.1.168
          ansible_host: claude.local
          ansible_user: pi
        georgia:
          ansible_host: georgia.local
          ansible_user: pi

