---
- hosts: setup_cameras
  # use privilege escalation (sudo)
  become: yes

  tasks: 
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
    tags: [setup]

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
    tags: [setup]

  - name: Ensure git, pip & pipenv are installed
    apt:
      pkg:
      - git
      - python-pip
      - pipenv
      - nodejs
    tags: [setup]

  - name: Check if rws (raspi-webrtc-streamer) is installed
    command: dpkg-query -W rws
    register: check_rws_installed
    failed_when: check_rws_installed.rc > 1
    changed_when: check_rws_installed.rc == 1
    tags: [setup-rws]

  - name: Download rws Deb package
    get_url:
      url: "https://github.com/kclyu/rpi-webrtc-streamer-deb/raw/master/rws_0.74.1_RaspZeroW_armhf.deb"
      dest: "/home/pi/rws_0.74.1_RaspZeroW_armhf.deb"
    when: check_rws_installed.rc == 1
    tags: [setup-rws]

  - name: Install rws package
    apt: deb="/home/pi/rws_0.74.1_RaspZeroW_armhf.deb"
    when: check_rws_installed.rc == 1
    tags: [setup-rws]

  - name: checkout bloomcatcher repo
    become: no
    git:
      repo: git://github.com/dandelany/bloomcatcher.git
      dest: "/home/pi/bloomcatcher"
      version: master
      accept_hostkey: true
    tags: [setup, update]


